# Generated by Django 2.2.10 on 2020-04-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('capo', models.IntegerField()),
                ('edited', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('chords', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('deleted_lines', models.CharField(blank=True, max_length=200)),
                ('warning_lines', models.CharField(blank=True, max_length=200)),
                ('handled_lines', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('start_note', models.CharField(choices=[('-', '-'), ('a', 'A'), ('as', 'A#'), ('b', 'B'), ('c', 'C'), ('cs', 'C#'), ('d', 'D'), ('ds', 'D#'), ('e', 'E'), ('f', 'F'), ('fs', 'F#'), ('g', 'G'), ('gs', 'G#')], default='-', max_length=2)),
            ],
            options={
                'unique_together': {('artist', 'title')},
            },
        ),
    ]
