# Generated by Django 2.2.4 on 2019-08-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patacrep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('capo', models.IntegerField()),
                ('nbcol', models.IntegerField()),
                ('edited', models.BooleanField(default=False)),
                ('chords', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
