# Generated by Django 2.2.4 on 2019-08-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patacrep', '0002_chord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chord',
            unique_together={('artist', 'title')},
        ),
    ]
