# Generated by Django 2.2.4 on 2019-08-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patacrep', '0003_auto_20190820_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='removed_content_confirmation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chord',
            name='warning_lines',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
