# Generated by Django 2.2.4 on 2019-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patacrep', '0004_auto_20190823_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chord',
            name='removed_content_confirmation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='chord',
            name='warning_lines',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
