# Generated by Django 2.2.4 on 2019-08-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patacrep', '0005_auto_20190824_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chord',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chord',
            name='start_note',
            field=models.CharField(choices=[('-', '-'), ('A', 'A'), ('A#', 'A#'), ('B', 'B'), ('C', 'C'), ('C#', 'C#'), ('D', 'D'), ('D#', 'D#'), ('E', 'E'), ('F', 'F'), ('F#', 'F#'), ('G', 'G'), ('G#', 'G#')], default='-', max_length=2),
        ),
    ]
